

function py2js_str(v) {
    if (v && v.toFixed) {
        if (Math.floor(v) != v) {
            return v.toFixed(12);
        }
    }
    return new String(v);
}


// generated by py2js from tests/modules/from_import.py


var __name__ = '__main__';

// generated by py2js from tests/modules/imported/modulea.py


__name__ = 'imported.modulea';


// __main__->imported.modulea
var imported = {};
imported.modulea = {};
imported.modulea.modulea_fn = function()  {
    console.log(String('import_modulea.modulea_fn()'));
}


imported.modulea.modulea_class = function()  {
    
    if (arguments.length==1 && arguments[0] == undefined) { return; }
    
    var self = new imported.modulea.modulea_class(undefined);
    
    self.msg = function(val) { return imported.modulea.modulea_class.msg(this,val); }
    
    imported.modulea.modulea_class.__init__(self);
    
    return self;
}

imported.modulea.modulea_class.__init__ = function(self)  {
    /* pass */
}
imported.modulea.modulea_class.msg = function(self,val)  {
    return ('modulea_class:' + py2js_str(val));
}
imported.modulea.modulea_class.super = function(self) {
    this.self = self;
    return this;
}




__name__ = '__main__';


// generated by py2js from tests/modules/imported/moduleb.py


__name__ = 'imported.moduleb';


// __main__->imported.moduleb
imported.moduleb = {};
imported.moduleb.foo = function()  {
    console.log(String('foo'));
}
imported.moduleb.moduleb_fn = function()  {
    console.log(String('import_moduleb.moduleb_fn()'));
}


imported.moduleb.moduleb_class = function()  {
    
    if (arguments.length==1 && arguments[0] == undefined) { return; }
    
    var self = new imported.moduleb.moduleb_class(undefined);
    
    self.msg = function(val) { return imported.moduleb.moduleb_class.msg(this,val); }
    
    imported.moduleb.moduleb_class.__init__(self);
    
    return self;
}

imported.moduleb.moduleb_class.__init__ = function(self)  {
    /* pass */
}
imported.moduleb.moduleb_class.msg = function(self,val)  {
    return ('moduleb_class:' + py2js_str(val));
}
imported.moduleb.moduleb_class.super = function(self) {
    this.self = self;
    return this;
}




__name__ = '__main__';


// generated by py2js from tests/modules/imported/modulec.py


__name__ = '';


// __main__->
// generated by py2js from tests/modules/imported/submodules/submodulea.py


__name__ = 'submodules.submodulea';


// ->submodules.submodulea
var submodules = {};
submodules.submodulea = {};
submodules.submodulea.foo = function()  {
    console.log(String('imported.modules.submodules.modulea.foo()'));
}



__name__ = '';


foo = function()  {
    console.log(String('imported.modulec.foo()'));
    submodules.submodulea.foo();
}



__name__ = '__main__';


imported.modulea.modulea_fn();
imported.moduleb.moduleb_fn();
foo();
