

function py2js_str(v) {
    if (v && v.toFixed) {
        if (Math.floor(v) != v) {
            return v.toFixed(12);
        }
    }
    return new String(v);
}


// generated by py2js from tests/modules/import_diamond.py


var __name__ = '__main__';

// generated by py2js from tests/modules/modules/diamond1.py


__name__ = 'modules.diamond1';


// __main__->modules.diamond1
// generated by py2js from tests/modules/modules/submodules/diamondbase.py


__name__ = 'modules.submodules.diamondbase';


// modules.diamond1->modules.submodules.diamondbase

var modules = {};
modules.submodules = {};
modules.submodules.diamondbase = {};
modules.submodules.diamondbase.counter=0;
modules.submodules.diamondbase.run = function()  {
    
    
    modules.submodules.diamondbase.counter += 1;
    console.log(String((('diamondbase called ' + py2js_str(modules.submodules.diamondbase.counter)) + ' time(s)')));
}



__name__ = 'modules.diamond1';


modules.diamond1 = {};
modules.diamond1.run = function()  {
    console.log(String('calling diamond1.run()'));
    modules.submodules.diamondbase.run();
}



__name__ = '__main__';


// generated by py2js from tests/modules/modules/diamond2.py


__name__ = 'modules.diamond2';


// __main__->modules.diamond2
modules.diamond2 = {};
modules.diamond2.run = function()  {
    console.log(String('Calling diamond2.run()'));
    modules.submodules.diamondbase.run();
}



__name__ = '__main__';


modules.diamond1.run();
modules.diamond2.run();
