// generated by py2js from tests/modules/import_alias.py


var __name__ = '__main__';

// generated by py2js from tests/modules/imported/alias_fns.py


__name__ = 'imported.alias_fns';


// __main__->imported.alias_fns
var imported = {};
imported.alias_fns = {};
imported.alias_fns.foo = function()  {
    console.log(String('this is foo'));
}



__name__ = '__main__';


// generated by py2js from tests/modules/imported/alias_classes.py


__name__ = 'imported.alias_classes';


// __main__->imported.alias_classes
imported.alias_classes = {};


imported.alias_classes.spam = function()  {
    
    if (arguments.length==1 && arguments[0] == undefined) { return; }
    
    var self = new imported.alias_classes.spam(undefined);
    
    self.msg = function() { return imported.alias_classes.spam.msg(this); }
    
    imported.alias_classes.spam.__init__(self);
    
    return self;
}

imported.alias_classes.spam.__init__ = function(self)  {
    self.msgtxt='this is spam';
}
imported.alias_classes.spam.msg = function(self)  {
    console.log(String(self.msgtxt));
}
imported.alias_classes.spam.super = function(self) {
    this.self = self;
    return this;
}

if (__name__ == '__main__') {
    
    imported.alias_classes.s=imported.alias_classes.spam();
    imported.alias_classes.s.msg();
}



__name__ = '__main__';


imported.alias_fns.foo();

e=imported.alias_classes.spam();
e.msg();
