// generated by py2js from tests/modules/import_class.py


var __name__ = '__main__';

// generated by py2js from tests/modules/modules/klasses.py


__name__ = 'modules.klasses';


// __main__->modules.klasses
var modules = {};
modules.klasses = {};


modules.klasses.baseklass = function()  {
    
    if (arguments.length==1 && arguments[0] == undefined) { return; }
    
    var self = new modules.klasses.baseklass(undefined);
    
    self.sayhello = function() { return modules.klasses.baseklass.sayhello(); }
    
    return self;
}

modules.klasses.baseklass.sayhello = function()  {
    console.log(String('baseklass says hello'));
}
modules.klasses.baseklass.super = function(self) {
    this.self = self;
    return this;
}



modules.klasses.klass = function()  {
    
    if (arguments.length==1 && arguments[0] == undefined) { return; }
    
    var self = new modules.klasses.klass(undefined);
    
    self.sayhello = function() { return modules.klasses.baseklass.sayhello(); }
    
    return self;
}

/* modules.klasses.klass.sayhello->modules.klasses.baseklass */
modules.klasses.klass.super = function(self) {
    this.self = self;
    this.sayhello = function() { return modules.klasses.baseklass.sayhello(); }
    return this;
}

if (__name__ == '__main__') {
    
    modules.klasses.k=modules.klasses.klass();
    modules.klasses.k.sayhello();
    modules.klasses.klass.sayhello();
    modules.klasses.baseklass.sayhello();
}



__name__ = '__main__';



k=modules.klasses.klass();
k.sayhello();
modules.klasses.baseklass.sayhello();
