// generated by py2js from tests/modules/module_name.py


var __name__ = '__main__';

// generated by py2js from tests/modules/modules/module_name.py


__name__ = 'modules.module_name';


// __main__->modules.module_name
// generated by py2js from tests/modules/modules/submodules/module_name.py


__name__ = 'modules.submodules.module_name';


// modules.module_name->modules.submodules.module_name
console.log(String(('3rd level module __name__:' + __name__)));



__name__ = 'modules.module_name';


console.log(String(('2nd level module __name__:' + __name__)));



__name__ = '__main__';


console.log(String(('1st level module __name__:' + __name__)));
