


function Generator(container) {
        var isarray = (container instanceof Array);
        var isstring = (typeof(container) == 'string');
        if (container.__iter__) {
                this.values = [];
                this.iterator = container.__iter__();
        } else if (isarray || isstring) {
                this.values = container;
        } else {
                this.values = [];
                for(key in container) {
                        this.values.push(key);
                }
        }
        this.index = 0;
}

Generator.prototype.nextValue = function() {
        if (this.iterator) {
                try {
                        return this.iterator.next();
                } catch( e ) {
                        this.iterator_exhausted = true;
                        return null;
                }
        }
        else if (this.index < this.values.length) {
                return this.values[this.index++];
        } else {
                this.index++;
                return null;
        }
}

Generator.prototype.hadMore = function() {
        if (this.iterator_exhausted) {
                return false;
        }
        return (this.index-1) < this.values.length;
}





function py2js_extend(list1,list2) {
    var i;
    for(i=0;i<list2.length;i++) {
        list1.push(list2[i]);
    }    
}


// generated by py2js from tests/lists/extend.py


var __name__ = '__main__';


list1=[1,2,'f',44];

list2=['a',99,77];

list3=list1.slice(0,list1.length);
py2js_extend(list3,list2);


container_py2js_1=list3;
var generator_py2js_2 = new Generator(container_py2js_1);
for(item=generator_py2js_2.nextValue();generator_py2js_2.hadMore();item=generator_py2js_2.nextValue()) {
    console.log(String(item));
}
