

function py2js_str(v) {
    if (v && v.toFixed) {
        if (Math.floor(v) != v) {
            return v.toFixed(12);
        }
    }
    return new String(v);
}




function py2js_in(item,container) {
        if (container instanceof Array) {
            return container.indexOf(item) != -1;
        }
        return item in container;
}


// generated by py2js from tests/lists/in.py


var __name__ = '__main__';


l=['a','b','c'];
function intest(item,list)  {
    if (py2js_in(item,list)) {
        console.log(String((py2js_str(item) + ' is in list')));
    }else  {
        console.log(String((py2js_str(item) + ' is not in list')));
    }
}
intest('a',l);
intest('b',l);
intest(99,l);
intest(0,l);
intest('z',l);
intest('c',l);
