
function py2js_minmax(list,minNotMax) {
    var result = null;
    /* FIXME should throw ValueError if list is empty */    
    for(i=0;i<list.length;i++) {
        if ((result == null) || (minNotMax && list[i]<result) || (!minNotMax && list[i]>result)) {
            result = list[i];
        }
    }    
    return result;
}


// generated by py2js from tests/lists/min.py


var __name__ = '__main__';


l=[4,7,3,4,2,1];

v=py2js_minmax(l,true);
console.log(String(v));
