
function py2js_reduce(fn,list) {
    var pos = 0;
    var result = null;
    if (arguments.length == 3) {
        result = arguments[2];
    }
    if (result == null) {
        pos = 1;
        result = list[0];    
    }

    for(i=pos;i<list.length;i++) {
        result = fn(result,list[i]);
    }    

    return result;
}


// generated by py2js from tests/lists/reduce.py


var __name__ = '__main__';

function foo(x,y)  {
    return (x * y);
}

y=[1,2,3,4,5];

z=py2js_reduce(foo,y,10);
console.log(String(z));

z=py2js_reduce(foo,y);
console.log(String(z));
