
function py2js_zip() {
    
    if (arguments.length == 0) {
        return [];
    }

    var results = [];
    var pos = -1;
    var i = 0;
    var cont = true;
    while(cont) {
        pos++;
        for(i=0;i<arguments.length;i++) {
            if (pos >= arguments[i].length) {
                cont = false;
                break;
            }
        }
        if (cont) {
            var newitem = [];
            for(i=0; i<arguments.length;i++) {
               newitem.push(arguments[i][pos]);
            }
            results.push(newitem);
        }
    }
    return results;
}





function Generator(container) {
        var isarray = (container instanceof Array);
        var isstring = (typeof(container) == 'string');
        if (container.__iter__) {
                this.values = [];
                this.iterator = container.__iter__();
        } else if (isarray || isstring) {
                this.values = container;
        } else {
                this.values = [];
                for(key in container) {
                        this.values.push(key);
                }
        }
        this.index = 0;
}

Generator.prototype.nextValue = function() {
        if (this.iterator) {
                try {
                        return this.iterator.next();
                } catch( e ) {
                        this.iterator_exhausted = true;
                        return null;
                }
        }
        else if (this.index < this.values.length) {
                return this.values[this.index++];
        } else {
                this.index++;
                return null;
        }
}

Generator.prototype.hadMore = function() {
        if (this.iterator_exhausted) {
                return false;
        }
        return (this.index-1) < this.values.length;
}




// generated by py2js from tests/lists/zip.py


var __name__ = '__main__';


l1=[1,2,3,4,5];

l2=[5,4,3,2,1];

l3=[4,4,4,4];

l4=py2js_zip(l1,l2,l3);


container_py2js_1=l4;
var generator_py2js_2 = new Generator(container_py2js_1);
for(item=generator_py2js_2.nextValue();generator_py2js_2.hadMore();item=generator_py2js_2.nextValue()) {
    console.log(String('---'));
    
    
    container_py2js_3=item;
    var generator_py2js_4 = new Generator(container_py2js_3);
    for(val=generator_py2js_4.nextValue();generator_py2js_4.hadMore();val=generator_py2js_4.nextValue()) {
        console.log(String(val));
    }
}
