// generated by py2js from tests/functions/append.py


var __name__ = '__main__';


mylist=[];
mylist.push('a');
mylist.push('b');
mylist.push('c');
console.log(String((mylist[0])));
console.log(String((mylist[1])));
console.log(String((mylist[2])));
