// generated by py2js from tests/functions/aug.py


var __name__ = '__main__';


a=244;

b=23;
console.log(String(a));

a += 4;
console.log(String(a));

a -= 2;
console.log(String(a));

a <<= 4;
console.log(String(a));

a >>= 2;
console.log(String(a));

a |= 234324;
console.log(String(a));

a &= 213213;
console.log(String(a));

a ^= 2312;
console.log(String(a));

a = Math.floor(a/324);
console.log(String(a));

a += 1;
console.log(String(a));

a /= 2;
console.log(String(a));
console.log(String(b));

b = Math.pow(b,3);
console.log(String(b));
