

function py2js_float(s) {
    var n = new Number(s);
    if (isNaN(n)) {
        // warning text nicked from python ValueError
        throw(new ValueError("invalid literal for float: "+String(s)));
    }
    return n;
}




function ValueError(details) {
    this.details = details;
    return this;
}


// generated by py2js from tests/functions/float.py


var __name__ = '__main__';


a='123.456';

b=py2js_float(a);
console.log(String(b));
