// generated by py2js from tests/functions/gtge.py


var __name__ = '__main__';


x=123;

y=233;

y2=233;

z=892;
if (x > y) {
    console.log(String('x > y - incorrect'));
}else  {
    console.log(String('not x > y - correct'));
}
if (y >= y2) {
    console.log(String('y >= y2 - correct'));
}else  {
    console.log(String('not y >= y2 - incorrect'));
}
if (z > x) {
    console.log(String('z > x - correct'));
}else  {
    console.log(String('not z > x - incorrect'));
}
if (y >= z) {
    console.log(String('y >= z - incorrect'));
}else  {
    console.log(String('not y >= x - correct'));
}
