

function py2js_in(item,container) {
        if (container instanceof Array) {
            return container.indexOf(item) != -1;
        }
        return item in container;
}


// generated by py2js from tests/functions/in.py


var __name__ = '__main__';


a={1:'aaa','b':2};
if (py2js_in(2,a)) {
    console.log(String('2 in a - incorrect'));
}
if (py2js_in('b',a)) {
    console.log(String('b in a - correct'));
}
if (py2js_in(1,a)) {
    console.log(String('1 in a - correct'));
}
if (!(3 in a)) {
    console.log(String('3 not in a - correct'));
}
if (!('x' in a)) {
    console.log(String('x not in a - correct'));
}
