

function py2js_int(s) {
    if (typeof(s) == 'string' && s.indexOf('.') != -1) {
        throw(new ValueError("invalid literal for int: "+String(s)));
    }
    var n = new Number(s);
    if (isNaN(n)) {
        // warning text nicked from python ValueError
        throw(new ValueError("invalid literal for int: "+String(s)));
    }
    if (n < 0) {
        n = -Math.floor(Math.abs(n));
    } else {
        n = Math.floor(n);
    }        
    return n;
}





function ValueError(details) {
    this.details = details;
    return this;
}


// generated by py2js from tests/functions/int.py


var __name__ = '__main__';


x='123';

y=py2js_int(x);
console.log(String(y));
