

function py2js_len(container) {
        if (container instanceof Array) {
            return container.length;
        }
        var i;
        var count = 0;
        for (i in container) {
            count++;
        }
        return count;
}


// generated by py2js from tests/functions/len.py


var __name__ = '__main__';


mylist=[1,2,3];
console.log(String(py2js_len(mylist)));
