

function py2js_str(v) {
    if (v && v.toFixed) {
        if (Math.floor(v) != v) {
            return v.toFixed(12);
        }
    }
    return new String(v);
}





function Generator(container) {
        var isarray = (container instanceof Array);
        var isstring = (typeof(container) == 'string');
        if (container.__iter__) {
                this.values = [];
                this.iterator = container.__iter__();
        } else if (isarray || isstring) {
                this.values = container;
        } else {
                this.values = [];
                for(key in container) {
                        this.values.push(key);
                }
        }
        this.index = 0;
}

Generator.prototype.nextValue = function() {
        if (this.iterator) {
                try {
                        return this.iterator.next();
                } catch( e ) {
                        this.iterator_exhausted = true;
                        return null;
                }
        }
        else if (this.index < this.values.length) {
                return this.values[this.index++];
        } else {
                this.index++;
                return null;
        }
}

Generator.prototype.hadMore = function() {
        if (this.iterator_exhausted) {
                return false;
        }
        return (this.index-1) < this.values.length;
}




// generated by py2js from tests/functions/ne.py


var __name__ = '__main__';



container_py2js_1=[[1,2],['aaa','bbb'],[4,4],['a','a']];
var generator_py2js_2 = new Generator(container_py2js_1);
for(loop_py2js_3=generator_py2js_2.nextValue();generator_py2js_2.hadMore();loop_py2js_3=generator_py2js_2.nextValue()) {
    [x,y]=loop_py2js_3;
    if (x != y) {
        console.log(String(((py2js_str(x) + ' <> ') + py2js_str(y))));
    }else  {
        console.log(String(((('not: ' + py2js_str(x)) + ' <> ') + py2js_str(y))));
    }
}
