
function py2js_sort3(lst,fn,ky,rv) {
    sfn = function(a,b) {
        if (!rv) {
            return fn(ky(a),ky(b));
        } else {
            return fn(ky(b),ky(a));
        }    
    }
    lst.sort(sfn);
}


// generated by py2js from tests/functions/sort23.py


var __name__ = '__main__';

function getkey(x)  {
    if (x < 5) {
        return (x + 10);
    }else  {
        return x;
    }
}
function revcmp(a,b)  {
    if (b < a) {
        return -1;
    }
    if (b == a) {
        return 0;
    }
    return 1;
}

l=[4,7,2,3,8,1,3];
py2js_sort3(l,revcmp,getkey,false);
console.log(String((l[0])));
console.log(String((l[1])));
console.log(String((l[2])));
console.log(String('---'));
py2js_sort3(l,revcmp,getkey,true);
console.log(String((l[0])));
console.log(String((l[1])));
console.log(String((l[2])));
