

function py2js_str(v) {
    if (v && v.toFixed) {
        if (Math.floor(v) != v) {
            return v.toFixed(12);
        }
    }
    return new String(v);
}


// generated by py2js from tests/functions/str.py


var __name__ = '__main__';


a=1;

b=py2js_str(a);

c='x: ' + b;
console.log(String(a));
console.log(String(b));
console.log(String(c));
