


function Generator(container) {
        var isarray = (container instanceof Array);
        var isstring = (typeof(container) == 'string');
        if (container.__iter__) {
                this.values = [];
                this.iterator = container.__iter__();
        } else if (isarray || isstring) {
                this.values = container;
        } else {
                this.values = [];
                for(key in container) {
                        this.values.push(key);
                }
        }
        this.index = 0;
}

Generator.prototype.nextValue = function() {
        if (this.iterator) {
                try {
                        return this.iterator.next();
                } catch( e ) {
                        this.iterator_exhausted = true;
                        return null;
                }
        }
        else if (this.index < this.values.length) {
                return this.values[this.index++];
        } else {
                this.index++;
                return null;
        }
}

Generator.prototype.hadMore = function() {
        if (this.iterator_exhausted) {
                return false;
        }
        return (this.index-1) < this.values.length;
}




// generated by py2js from tests/basic/assign_slice.py


var __name__ = '__main__';


a=[1,2,3,4,5,6,7];
var upb_py2js_4=6;
var slice_py2js_1=['a','b'];
var loop_py2js_2;
var counter_py2js_3=0;
for(loop_py2js_2=4;loop_py2js_2<upb_py2js_4;loop_py2js_2+=1 ) {
    if ( counter_py2js_3 < slice_py2js_1.length) {
        a[loop_py2js_2] = slice_py2js_1[counter_py2js_3];
    } else {
        a.splice(loop_py2js_2,1);
        loop_py2js_2--;
        upb_py2js_4--;
    }
    counter_py2js_3++;
}
while ( counter_py2js_3 < slice_py2js_1.length) {
    a.splice(loop_py2js_2,0,slice_py2js_1[counter_py2js_3]);
    counter_py2js_3++;
    loop_py2js_2++;
}
function show(x)  {
    console.log(String('----'));
    var x;
    var container_py2js_5;
    container_py2js_5=a;
    var generator_py2js_6 = new Generator(container_py2js_5);
    for(x=generator_py2js_6.nextValue();generator_py2js_6.hadMore();x=generator_py2js_6.nextValue()) {
        console.log(String(x));
    }
}
show(a);
var upb_py2js_10=4;
var slice_py2js_7=['z'];
var loop_py2js_8;
var counter_py2js_9=0;
for(loop_py2js_8=2;loop_py2js_8<upb_py2js_10;loop_py2js_8+=1 ) {
    if ( counter_py2js_9 < slice_py2js_7.length) {
        a[loop_py2js_8] = slice_py2js_7[counter_py2js_9];
    } else {
        a.splice(loop_py2js_8,1);
        loop_py2js_8--;
        upb_py2js_10--;
    }
    counter_py2js_9++;
}
while ( counter_py2js_9 < slice_py2js_7.length) {
    a.splice(loop_py2js_8,0,slice_py2js_7[counter_py2js_9]);
    counter_py2js_9++;
    loop_py2js_8++;
}
show(a);
var upb_py2js_14=2;
var slice_py2js_11=['abc','def','abc','def'];
var loop_py2js_12;
var counter_py2js_13=0;
for(loop_py2js_12=0;loop_py2js_12<upb_py2js_14;loop_py2js_12+=1 ) {
    if ( counter_py2js_13 < slice_py2js_11.length) {
        a[loop_py2js_12] = slice_py2js_11[counter_py2js_13];
    } else {
        a.splice(loop_py2js_12,1);
        loop_py2js_12--;
        upb_py2js_14--;
    }
    counter_py2js_13++;
}
while ( counter_py2js_13 < slice_py2js_11.length) {
    a.splice(loop_py2js_12,0,slice_py2js_11[counter_py2js_13]);
    counter_py2js_13++;
    loop_py2js_12++;
}
show(a);
