// generated by py2js from tests/basic/class.py


var __name__ = '__main__';



function foobar()  {
    
    if (arguments.length==1 && arguments[0] == undefined) { return; }
    
    var self = new foobar(undefined);
    
    self.foo = function(x) { return foobar.foo(this,x); }
    
    self.bar = function() { return foobar.bar(this); }
    
    foobar.__init__(self);
    
    return self;
}

foobar.__init__ = function(self)  {
    self.foovar=1;
}
foobar.foo = function(self,x)  {
    self.foovar=self.foovar + x;
}
foobar.bar = function(self)  {
    console.log(String(self.foovar));
}

foobar.x=1;
foobar.super = function(self) {
    this.self = self;
    return this;
}


f=foobar();
f.bar();
f.foo(1);
f.foo(2);
f.bar();
f.bar();
f.foo(-1);
f.bar();
f.foo(7);
f.bar();
