// generated by py2js from tests/basic/default.py


var __name__ = '__main__';


g=99;
function f(a,b,c,d)  {
    if (b == undefined) {
       b=1;
    }
    if (c == undefined) {
       c='default c';
    }
    if (d == undefined) {
       d=g;
    }
    console.log(String(a));
    console.log(String(b));
    console.log(String(c));
    console.log(String(d));
}
f(0);
f(0,77);
f(0,77,'hello');
