

function py2js_len(container) {
        if (container instanceof Array) {
            return container.length;
        }
        var i;
        var count = 0;
        for (i in container) {
            count++;
        }
        return count;
}


// generated by py2js from tests/basic/del_slice.py


var __name__ = '__main__';


mylist=[1,2,3,4,5];
var upb_py2js_4=3;
var slice_py2js_1=[];
var loop_py2js_2;
var counter_py2js_3=0;
for(loop_py2js_2=1;loop_py2js_2<upb_py2js_4;loop_py2js_2+=1 ) {
    if ( counter_py2js_3 < slice_py2js_1.length) {
        mylist[loop_py2js_2] = slice_py2js_1[counter_py2js_3];
    } else {
        mylist.splice(loop_py2js_2,1);
        loop_py2js_2--;
        upb_py2js_4--;
    }
    counter_py2js_3++;
}
while ( counter_py2js_3 < slice_py2js_1.length) {
    mylist.splice(loop_py2js_2,0,slice_py2js_1[counter_py2js_3]);
    counter_py2js_3++;
    loop_py2js_2++;
}

for(x=0;x<py2js_len(mylist);x+=1) {
    console.log(String((mylist[x])));
}
