

function py2js_len(container) {
        if (container instanceof Array) {
            return container.length;
        }
        var i;
        var count = 0;
        for (i in container) {
            count++;
        }
        return count;
}


// generated by py2js from tests/basic/del_array.py


var __name__ = '__main__';


mylist=[1,2,3,4,5];
if (mylist instanceof Array) {
    mylist.splice(3,1);
} else {
    delete mylist[3]
}

for(x=0;x<py2js_len(mylist);x+=1) {
    console.log(String((mylist[x])));
}
