

function py2js_in(item,container) {
        if (container instanceof Array) {
            return container.indexOf(item) != -1;
        }
        return item in container;
}


// generated by py2js from tests/basic/del_dict.py


var __name__ = '__main__';


mydict={};

(mydict['abc'])='def';

(mydict['def'])='abc';

(mydict['xyz'])='rst';
console.log(String((mydict['abc'])));
console.log(String((mydict['def'])));
console.log(String((mydict['xyz'])));
if (mydict instanceof Array) {
    mydict.splice('def',1);
} else {
    delete mydict['def']
}
if (py2js_in('abc',mydict)) {
    console.log(String('abc in mydict'));
}else  {
    console.log(String('abc not in mydict'));
}
if (py2js_in('def',mydict)) {
    console.log(String('def in mydict'));
}else  {
    console.log(String('def not in mydict'));
}
if (py2js_in('xyz',mydict)) {
    console.log(String('xyz in mydict'));
}else  {
    console.log(String('xyz not in mydict'));
}
