// generated by py2js from tests/basic/docstring.py


var __name__ = '__main__';



function myclass(msg)  {
    
    if (arguments.length==1 && arguments[0] == undefined) { return; }
    
    var self = new myclass(undefined);
    
    self.saysomething = function() { return myclass.saysomething(this); }
    
    myclass.__init__(self,msg);
    
    return self;
}

myclass.__init__ = function(self,msg)  {
    self.msg=msg;
}
myclass.saysomething = function(self)  {
    console.log(String(self.msg));
}
myclass.super = function(self) {
    this.self = self;
    return this;
}


m=myclass('hello');
m.saysomething();
