

function py2js_int(s) {
    if (typeof(s) == 'string' && s.indexOf('.') != -1) {
        throw(new ValueError("invalid literal for int: "+String(s)));
    }
    var n = new Number(s);
    if (isNaN(n)) {
        // warning text nicked from python ValueError
        throw(new ValueError("invalid literal for int: "+String(s)));
    }
    if (n < 0) {
        n = -Math.floor(Math.abs(n));
    } else {
        n = Math.floor(n);
    }        
    return n;
}





function ValueError(details) {
    this.details = details;
    return this;
}





function Generator(container) {
        var isarray = (container instanceof Array);
        var isstring = (typeof(container) == 'string');
        if (container.__iter__) {
                this.values = [];
                this.iterator = container.__iter__();
        } else if (isarray || isstring) {
                this.values = container;
        } else {
                this.values = [];
                for(key in container) {
                        this.values.push(key);
                }
        }
        this.index = 0;
}

Generator.prototype.nextValue = function() {
        if (this.iterator) {
                try {
                        return this.iterator.next();
                } catch( e ) {
                        this.iterator_exhausted = true;
                        return null;
                }
        }
        else if (this.index < this.values.length) {
                return this.values[this.index++];
        } else {
                this.index++;
                return null;
        }
}

Generator.prototype.hadMore = function() {
        if (this.iterator_exhausted) {
                return false;
        }
        return (this.index-1) < this.values.length;
}




// generated by py2js from tests/basic/float2int.py


var __name__ = '__main__';



container_py2js_1=[123.456,1.1,-0.00045,-1.45,1.5,1022423.22];
var generator_py2js_2 = new Generator(container_py2js_1);
for(f=generator_py2js_2.nextValue();generator_py2js_2.hadMore();f=generator_py2js_2.nextValue()) {
    
    i=py2js_int(f);
    console.log(String(i));
}
