


function Generator(container) {
        var isarray = (container instanceof Array);
        var isstring = (typeof(container) == 'string');
        if (container.__iter__) {
                this.values = [];
                this.iterator = container.__iter__();
        } else if (isarray || isstring) {
                this.values = container;
        } else {
                this.values = [];
                for(key in container) {
                        this.values.push(key);
                }
        }
        this.index = 0;
}

Generator.prototype.nextValue = function() {
        if (this.iterator) {
                try {
                        return this.iterator.next();
                } catch( e ) {
                        this.iterator_exhausted = true;
                        return null;
                }
        }
        else if (this.index < this.values.length) {
                return this.values[this.index++];
        } else {
                this.index++;
                return null;
        }
}

Generator.prototype.hadMore = function() {
        if (this.iterator_exhausted) {
                return false;
        }
        return (this.index-1) < this.values.length;
}




// generated by py2js from tests/basic/for_in.py


var __name__ = '__main__';


a=[1,2,3,4,5];


container_py2js_1=a;
var generator_py2js_2 = new Generator(container_py2js_1);
for(x=generator_py2js_2.nextValue();generator_py2js_2.hadMore();x=generator_py2js_2.nextValue()) {
    console.log(String(x));
}

a=['cats','dogs','squirrels'];


container_py2js_3=a;
var generator_py2js_4 = new Generator(container_py2js_3);
for(x=generator_py2js_4.nextValue();generator_py2js_4.hadMore();x=generator_py2js_4.nextValue()) {
    console.log(String(x));
}

a={'a':1,'b':2,'c':3};

keys=[];


container_py2js_5=a;
var generator_py2js_6 = new Generator(container_py2js_5);
for(x=generator_py2js_6.nextValue();generator_py2js_6.hadMore();x=generator_py2js_6.nextValue()) {
    keys.push(x);
}
keys.sort();


container_py2js_7=keys;
var generator_py2js_8 = new Generator(container_py2js_7);
for(k=generator_py2js_8.nextValue();generator_py2js_8.hadMore();k=generator_py2js_8.nextValue()) {
    console.log(String(k));
}

a='defabc';


container_py2js_9=a;
var generator_py2js_10 = new Generator(container_py2js_9);
for(x=generator_py2js_10.nextValue();generator_py2js_10.hadMore();x=generator_py2js_10.nextValue()) {
    console.log(String(x));
}
