
function Kwarg(dict) {
    this.dict = dict;
}
Kwarg.prototype.getDict = function() {
    return this.dict;
}





function Generator(container) {
        var isarray = (container instanceof Array);
        var isstring = (typeof(container) == 'string');
        if (container.__iter__) {
                this.values = [];
                this.iterator = container.__iter__();
        } else if (isarray || isstring) {
                this.values = container;
        } else {
                this.values = [];
                for(key in container) {
                        this.values.push(key);
                }
        }
        this.index = 0;
}

Generator.prototype.nextValue = function() {
        if (this.iterator) {
                try {
                        return this.iterator.next();
                } catch( e ) {
                        this.iterator_exhausted = true;
                        return null;
                }
        }
        else if (this.index < this.values.length) {
                return this.values[this.index++];
        } else {
                this.index++;
                return null;
        }
}

Generator.prototype.hadMore = function() {
        if (this.iterator_exhausted) {
                return false;
        }
        return (this.index-1) < this.values.length;
}




// generated by py2js from tests/basic/kwargs.py


var __name__ = '__main__';

function myfunc(a,b)  {
    var _py2js_1= arguments.length;
    var _py2js_2= arguments[arguments.length-1];
    var d = {};
    if (_py2js_2 instanceof Kwarg) {
        d = _py2js_2.getDict();
        _py2js_1--;
     } 
    var c= [];
    for(_py2js_3=2;_py2js_3<_py2js_1;_py2js_3++) {
        c.push(arguments[_py2js_3]);
    }
    console.log(String(a));
    console.log(String(b));
    var i;
    var container_py2js_4;
    container_py2js_4=c;
    var generator_py2js_5 = new Generator(container_py2js_4);
    for(i=generator_py2js_5.nextValue();generator_py2js_5.hadMore();i=generator_py2js_5.nextValue()) {
        console.log(String(i));
    }
    var i;
    var container_py2js_6;
    container_py2js_6=d;
    var generator_py2js_7 = new Generator(container_py2js_6);
    for(i=generator_py2js_7.nextValue();generator_py2js_7.hadMore();i=generator_py2js_7.nextValue()) {
        console.log(String(i));
        console.log(String((d[i])));
    }
}
myfunc(1,2,new Kwarg({bar:'a',foo:'c'}));
