// generated by py2js from tests/basic/list.py


var __name__ = '__main__';


x=[1,2,3,'a','b','c'];

y=x.slice(2,4);
console.log(String((x[0])));
console.log(String((x[3])));
console.log(String((y[0])));
console.log(String((y[1])));
