// generated by py2js from tests/basic/literals.py


var __name__ = '__main__';


a=1.234;

b=3;

c=3.45;

d='cats';
console.log(String(a));
console.log(String(b));
console.log(String(c));
console.log(String(d));
