// generated by py2js from tests/basic/logicalops.py


var __name__ = '__main__';


x=true;

y=false;

z=! y;
if (x) {
    console.log(String('x'));
}
if (y) {
    console.log(String('y'));
}
if (z) {
    console.log(String('z'));
}
