// generated by py2js from tests/basic/nestedclass.py


var __name__ = '__main__';



function foo()  {
    
    if (arguments.length==1 && arguments[0] == undefined) { return; }
    
    var self = new foo(undefined);
    
    self.msg = function() { return foo.msg(this); }
    
    self.bar=foo.bar;
    
    return self;
}

foo.msg = function(self)  {
    console.log(String('foo'));
    var b;
    b=self.bar();
    b.msg();
}
foo.super = function(self) {
    this.self = self;
    return this;
}



foo.bar = function()  {
    
    if (arguments.length==1 && arguments[0] == undefined) { return; }
    
    var self = new foo.bar(undefined);
    
    self.msg = function() { return foo.bar.msg(this); }
    
    return self;
}

foo.bar.msg = function(self)  {
    console.log(String('bar'));
}
foo.bar.super = function(self) {
    this.self = self;
    return this;
}


f=foo.bar();
f.msg();

f=foo();
f.msg();
