// generated by py2js from tests/basic/none.py


var __name__ = '__main__';


x=null;
if (x == null) {
    console.log(String('x is None/null'));
}else  {
    console.log(String('x is not None/null'));
}
