

function py2js_str(v) {
    if (v && v.toFixed) {
        if (Math.floor(v) != v) {
            return v.toFixed(12);
        }
    }
    return new String(v);
}





function Generator(container) {
        var isarray = (container instanceof Array);
        var isstring = (typeof(container) == 'string');
        if (container.__iter__) {
                this.values = [];
                this.iterator = container.__iter__();
        } else if (isarray || isstring) {
                this.values = container;
        } else {
                this.values = [];
                for(key in container) {
                        this.values.push(key);
                }
        }
        this.index = 0;
}

Generator.prototype.nextValue = function() {
        if (this.iterator) {
                try {
                        return this.iterator.next();
                } catch( e ) {
                        this.iterator_exhausted = true;
                        return null;
                }
        }
        else if (this.index < this.values.length) {
                return this.values[this.index++];
        } else {
                this.index++;
                return null;
        }
}

Generator.prototype.hadMore = function() {
        if (this.iterator_exhausted) {
                return false;
        }
        return (this.index-1) < this.values.length;
}




// generated by py2js from tests/basic/oo.py


var __name__ = '__main__';



function foo(val)  {
    
    if (arguments.length==1 && arguments[0] == undefined) { return; }
    
    var self = new foo(undefined);
    
    self.msg = function() { return foo.msg(this); }
    
    self.register = function(f) { return foo.register(f); }
    
    self.printregistered = function() { return foo.printregistered(); }
    
    self.inc = function() { return foo.inc(this); }
    
    foo.__init__(self,val);
    
    return self;
}

foo.__init__ = function(self,val)  {
    self.fval=val;
    self.register(self);
}
foo.msg = function(self)  {
    return ('foo says:' + py2js_str(self.fval));
}
foo.register = function(f)  {
    foo.registered.push(f);
}
foo.printregistered = function()  {
    var r;
    var container_py2js_1;
    container_py2js_1=foo.registered;
    var generator_py2js_2 = new Generator(container_py2js_1);
    for(r=generator_py2js_2.nextValue();generator_py2js_2.hadMore();r=generator_py2js_2.nextValue()) {
        console.log(String(r.msg()));
    }
}
foo.inc = function(self)  {
    self.fval += 1;
}

foo.registered=[];
foo.super = function(self) {
    this.self = self;
    return this;
}


a=foo(10);

b=foo(20);

c=foo(30);
a.inc();
a.inc();
c.inc();
console.log(String(a.msg()));
console.log(String(b.msg()));
console.log(String(c.msg()));
console.log(String('---'));
foo.printregistered();
