

function py2js_str(v) {
    if (v && v.toFixed) {
        if (Math.floor(v) != v) {
            return v.toFixed(12);
        }
    }
    return new String(v);
}





function Generator(container) {
        var isarray = (container instanceof Array);
        var isstring = (typeof(container) == 'string');
        if (container.__iter__) {
                this.values = [];
                this.iterator = container.__iter__();
        } else if (isarray || isstring) {
                this.values = container;
        } else {
                this.values = [];
                for(key in container) {
                        this.values.push(key);
                }
        }
        this.index = 0;
}

Generator.prototype.nextValue = function() {
        if (this.iterator) {
                try {
                        return this.iterator.next();
                } catch( e ) {
                        this.iterator_exhausted = true;
                        return null;
                }
        }
        else if (this.index < this.values.length) {
                return this.values[this.index++];
        } else {
                this.index++;
                return null;
        }
}

Generator.prototype.hadMore = function() {
        if (this.iterator_exhausted) {
                return false;
        }
        return (this.index-1) < this.values.length;
}




// generated by py2js from tests/basic/oo_inherit.py


var __name__ = '__main__';



function bar(name)  {
    
    if (arguments.length==1 && arguments[0] == undefined) { return; }
    
    var self = new bar(undefined);
    
    self.setname = function(name) { return bar.setname(this,name); }
    
    bar.__init__(self,name);
    
    return self;
}

bar.__init__ = function(self,name)  {
    self.name=name;
}
bar.setname = function(self,name)  {
    self.name=name;
}
bar.super = function(self) {
    this.self = self;
    return this;
}



function foo(val,name)  {
    
    if (arguments.length==1 && arguments[0] == undefined) { return; }
    
    var self = new foo(undefined);
    
    self.msg = function() {
    
        args = [this];
    
        for(var a=0;a<arguments.length;a++) {
    
            args.push(arguments[a]);
    
        }
    
        return foo.msg.apply(null,args);
    
    }
    
    self.register = function(f) { return foo.register(f); }
    
    self.setname = function(name) { return bar.setname(this,name); }
    
    self.printregistered = function() { return foo.printregistered(); }
    
    self.inc = function() { return foo.inc(this); }
    
    foo.__init__(self,val,name);
    
    return self;
}

foo.__init__ = function(self,val,name)  {
    self.fval=val;
    self.register(self);
    bar.__init__(self,name);
}
foo.msg = function(self)  {
    var _py2js_1= arguments.length;
    var varargs= [];
    for(_py2js_2=1;_py2js_2<_py2js_1;_py2js_2++) {
        varargs.push(arguments[_py2js_2]);
    }
    var txt;
    txt='';
    var arg;
    var container_py2js_3;
    container_py2js_3=varargs;
    var generator_py2js_4 = new Generator(container_py2js_3);
    for(arg=generator_py2js_4.nextValue();generator_py2js_4.hadMore();arg=generator_py2js_4.nextValue()) {
        var txt;
        txt += py2js_str(arg);
        var txt;
        txt += ',';
    }
    return (((txt + self.name) + ' says:') + py2js_str(self.fval));
}
foo.register = function(f)  {
    foo.registered.push(f);
}
foo.printregistered = function()  {
    var r;
    var container_py2js_5;
    container_py2js_5=foo.registered;
    var generator_py2js_6 = new Generator(container_py2js_5);
    for(r=generator_py2js_6.nextValue();generator_py2js_6.hadMore();r=generator_py2js_6.nextValue()) {
        console.log(String(r.msg()));
    }
}
foo.inc = function(self)  {
    self.fval += 1;
}

foo.registered=[];
foo.super = function(self) {
    this.self = self;
    this.__init__ = function(name) { return bar.__init__(this.self,name); }
    this.setname = function(name) { return bar.setname(this.self,name); }
    return this;
}


a=foo(10,'a');
a.setname('aaa');

b=foo(20,'b');

c=foo(30,'c');
a.inc();
a.inc();
c.inc();
console.log(String(a.msg()));
console.log(String(b.msg()));
console.log(String(c.msg(2,3,4)));
console.log(String('---'));
foo.printregistered();
