

function py2js_str(v) {
    if (v && v.toFixed) {
        if (Math.floor(v) != v) {
            return v.toFixed(12);
        }
    }
    return new String(v);
}


// generated by py2js from tests/basic/oo_static_inherit.py


var __name__ = '__main__';



function a1()  {
    
    if (arguments.length==1 && arguments[0] == undefined) { return; }
    
    var self = new a1(undefined);
    
    self.msg = function(val) { return a1.msg(val); }
    
    return self;
}

a1.msg = function(val)  {
    console.log(String(('a1 static method msg says:' + py2js_str(val))));
}
a1.super = function(self) {
    this.self = self;
    return this;
}



function a2()  {
    
    if (arguments.length==1 && arguments[0] == undefined) { return; }
    
    var self = new a2(undefined);
    
    self.msg = function(val) { return a1.msg(val); }
    
    return self;
}

/* a2.msg->a1 */
a2.super = function(self) {
    this.self = self;
    this.msg = function(val) { return a1.msg(val); }
    return this;
}


a=a2();
a.msg('hello');
a1.msg('world');
