// generated by py2js from tests/basic/pass.py


var __name__ = '__main__';


x='hello';
if (x != 'hello') {
    console.log(String('1'));
    /* pass */
    console.log(String('2'));
}else  {
    console.log(String('3'));
    /* pass */
    console.log(String('4'));
}
