// generated by py2js from tests/basic/scope.py


var __name__ = '__main__';


x=12;
function loopy()  {
    var x;
    for(x=0;x<8;x+=1) {
        console.log(String(x));
    }
}
loopy();
console.log(String(x));
