
function py2js_sum(list) {
    var i,total = 0;
    for(i=0;i<list.length;i++) {
        total += list[i];
    }    
    return total;
}





function Generator(container) {
        var isarray = (container instanceof Array);
        var isstring = (typeof(container) == 'string');
        if (container.__iter__) {
                this.values = [];
                this.iterator = container.__iter__();
        } else if (isarray || isstring) {
                this.values = container;
        } else {
                this.values = [];
                for(key in container) {
                        this.values.push(key);
                }
        }
        this.index = 0;
}

Generator.prototype.nextValue = function() {
        if (this.iterator) {
                try {
                        return this.iterator.next();
                } catch( e ) {
                        this.iterator_exhausted = true;
                        return null;
                }
        }
        else if (this.index < this.values.length) {
                return this.values[this.index++];
        } else {
                this.index++;
                return null;
        }
}

Generator.prototype.hadMore = function() {
        if (this.iterator_exhausted) {
                return false;
        }
        return (this.index-1) < this.values.length;
}




// generated by py2js from tests/basic/sumcomp.py


var __name__ = '__main__';


var comp_py2js_1= [];
 {
    
    
    container_py2js_2=[2,3,4,5,6,7];
    var generator_py2js_3 = new Generator(container_py2js_2);
    for(x=generator_py2js_3.nextValue();generator_py2js_3.hadMore();x=generator_py2js_3.nextValue()) {
        comp_py2js_1.push((x * x));
    }
}x=py2js_sum(comp_py2js_1);
console.log(String(x));
