

function py2js_str(v) {
    if (v && v.toFixed) {
        if (Math.floor(v) != v) {
            return v.toFixed(12);
        }
    }
    return new String(v);
}



function Kwarg(dict) {
    this.dict = dict;
}
Kwarg.prototype.getDict = function() {
    return this.dict;
}


// generated by py2js from tests/basic/super.py


var __name__ = '__main__';



function baseklass(bval)  {
    
    if (arguments.length==1 && arguments[0] == undefined) { return; }
    
    var self = new baseklass(undefined);
    
    self.describe2 = function() {
    
        args = [this];
    
        for(var a=0;a<arguments.length;a++) {
    
            args.push(arguments[a]);
    
        }
    
        return baseklass.describe2.apply(null,args);
    
    }
    
    self.describe = function(arg) { return baseklass.describe(this,arg); }
    
    baseklass.__init__(self,bval);
    
    return self;
}

baseklass.__init__ = function(self,bval)  {
    self.bval=bval;
}
baseklass.describe2 = function(self)  {
    var _py2js_1= arguments.length;
    var _py2js_2= arguments[arguments.length-1];
    var kwargs = {};
    if (_py2js_2 instanceof Kwarg) {
        kwargs = _py2js_2.getDict();
        _py2js_1--;
     } 
    console.log(String(((('baseklass.describe2:' + self.bval) + ':') + (kwargs['string']))));
}
baseklass.describe = function(self,arg)  {
    console.log(String(((('baseklass.describe:' + self.bval) + ':') + py2js_str(arg))));
}
baseklass.super = function(self) {
    this.self = self;
    return this;
}



function klass(val,bval)  {
    
    if (arguments.length==1 && arguments[0] == undefined) { return; }
    
    var self = new klass(undefined);
    
    self.describe2 = function() {
    
        args = [this];
    
        for(var a=0;a<arguments.length;a++) {
    
            args.push(arguments[a]);
    
        }
    
        return baseklass.describe2.apply(null,args);
    
    }
    
    self.describe = function() { return klass.describe(this); }
    
    klass.__init__(self,val,bval);
    
    return self;
}

klass.__init__ = function(self,val,bval)  {
    baseklass.__init__(self,bval);
    self.val=val;
}
klass.describe = function(self)  {
    klass.super(self).describe(10);
    klass.super(self).describe2(new Kwarg({string:'somestring'}));
    console.log(String(('klass.describe:' + self.val)));
}
klass.super = function(self) {
    this.self = self;
    this.describe2 = function() {
        args = [this.self];
        for(var a=0;a<arguments.length;a++) {
            args.push(arguments[a]);
        }
        return baseklass.describe2.apply(null,args);
    }
    this.describe = function(arg) { return baseklass.describe(this.self,arg); }
    this.__init__ = function(bval) { return baseklass.__init__(this.self,bval); }
    return this;
}


k=klass('world','hello');
k.describe();
