


function Generator(container) {
        var isarray = (container instanceof Array);
        var isstring = (typeof(container) == 'string');
        if (container.__iter__) {
                this.values = [];
                this.iterator = container.__iter__();
        } else if (isarray || isstring) {
                this.values = container;
        } else {
                this.values = [];
                for(key in container) {
                        this.values.push(key);
                }
        }
        this.index = 0;
}

Generator.prototype.nextValue = function() {
        if (this.iterator) {
                try {
                        return this.iterator.next();
                } catch( e ) {
                        this.iterator_exhausted = true;
                        return null;
                }
        }
        else if (this.index < this.values.length) {
                return this.values[this.index++];
        } else {
                this.index++;
                return null;
        }
}

Generator.prototype.hadMore = function() {
        if (this.iterator_exhausted) {
                return false;
        }
        return (this.index-1) < this.values.length;
}




// generated by py2js from tests/basic/trueorfalse.py


var __name__ = '__main__';


literals=['a','',0,null,1,0.0,1.0,-1,-1.0,0];


container_py2js_1=literals;
var generator_py2js_2 = new Generator(container_py2js_1);
for(l=generator_py2js_2.nextValue();generator_py2js_2.hadMore();l=generator_py2js_2.nextValue()) {
    if (l) {
        console.log(String('True'));
    }else  {
        console.log(String('False'));
    }
}
