// generated by py2js from tests/basic/tuple.py


var __name__ = '__main__';


tup=['a','b',1,2,3];
console.log(String((tup[0])));
console.log(String((tup[1])));
console.log(String((tup[2])));
console.log(String((tup[3])));
console.log(String((tup[4])));
