


function Generator(container) {
        var isarray = (container instanceof Array);
        var isstring = (typeof(container) == 'string');
        if (container.__iter__) {
                this.values = [];
                this.iterator = container.__iter__();
        } else if (isarray || isstring) {
                this.values = container;
        } else {
                this.values = [];
                for(key in container) {
                        this.values.push(key);
                }
        }
        this.index = 0;
}

Generator.prototype.nextValue = function() {
        if (this.iterator) {
                try {
                        return this.iterator.next();
                } catch( e ) {
                        this.iterator_exhausted = true;
                        return null;
                }
        }
        else if (this.index < this.values.length) {
                return this.values[this.index++];
        } else {
                this.index++;
                return null;
        }
}

Generator.prototype.hadMore = function() {
        if (this.iterator_exhausted) {
                return false;
        }
        return (this.index-1) < this.values.length;
}




// generated by py2js from tests/basic/vargs.py


var __name__ = '__main__';

function myfunc(a,b)  {
    var _py2js_1= arguments.length;
    var c= [];
    for(_py2js_2=2;_py2js_2<_py2js_1;_py2js_2++) {
        c.push(arguments[_py2js_2]);
    }
    console.log(String(a));
    console.log(String(b));
    var i;
    var container_py2js_3;
    container_py2js_3=c;
    var generator_py2js_4 = new Generator(container_py2js_3);
    for(i=generator_py2js_4.nextValue();generator_py2js_4.hadMore();i=generator_py2js_4.nextValue()) {
        console.log(String(i));
    }
}
myfunc(1,2);
myfunc('a','b','c','d');
myfunc(3,4,5,6,'hello');
