// generated by py2js from tests/basic/vars.py


var __name__ = '__main__';


x=1;

y=1;
function foo()  {
    var x;
    x=3;
    var x;
    x=x + 1;
    console.log(String(x));
}
function bar()  {
    
    
    y=3;
    
    y=y + 1;
    console.log(String(y));
}
foo();
bar();
console.log(String(x));
console.log(String(y));
