

function py2js_len(container) {
        if (container instanceof Array) {
            return container.length;
        }
        var i;
        var count = 0;
        for (i in container) {
            count++;
        }
        return count;
}



function py2js_count(str,sub,start,end) {
    var pos = 0;
    if (start != undefined) {
        if (start < 0) {
            start = str.length + start;
        }
        if (start < 0) {
            start = 0;
        }
        pos = start;
    }    
    if (end != undefined) {
        if (end < 0) {
            end = str.length + end;
        } 
        if (end < 0) {
            end = 0;
        }
    }
    pos = str.indexOf(sub,pos);
    var count = 0;
    while(pos >= 0) {
        if (end != undefined) {
            if (pos+sub.length > end) {
                break;
            }
        }
        count++;
        pos += sub.length;
        pos = str.indexOf(sub,pos);
    }
    return count;
}


// generated by py2js from tests/strings/count.py


var __name__ = '__main__';


txt='the quick brown fox jumped over the lazy dogthe';

c=py2js_count(txt,'the');
console.log(String(c));

c=py2js_count(txt,'the',0,-20);
console.log(String(c));

c=py2js_count(txt,'the',3);
console.log(String(c));

c=py2js_count(txt,'the',4,15);
console.log(String(c));

c=py2js_count(txt,'the',1,py2js_len(txt));
console.log(String(c));

c=py2js_count(txt,'the',4,(py2js_len(txt) - 1));
console.log(String(c));
