
function py2js_lstrip(str,chars) {
    var i = 0;    
    while(i < str.length) {
        if (chars.indexOf(str.slice(i,i+1)) == -1) {
            break;
        }            
        i++;
    }
    if (i == 0) {
        return str;
    }    
    if (i == str.length) {
        return "";
    }
    return str.slice(i);
}


// generated by py2js from tests/strings/lstrip1.py


var __name__ = '__main__';


s='abcxyz';
console.log(String((('original(' + s) + ')')));
console.log(String((('strip(' + py2js_lstrip(s,'cba')) + ')')));
