
function py2js_replace(str,mat,rep) {
    var s = str;    
    var pos = s.indexOf(mat,0);
    while(pos >= 0) {
        s = "".concat(s.slice(0,pos),rep,s.slice(pos+mat.length));
        pos = s.indexOf(mat,pos+rep.length);
    }
    return s;
}


// generated by py2js from tests/strings/replace.py


var __name__ = '__main__';


txt='the quick brown fox jumped over thethe lazy dog';

txt2=py2js_replace(txt,'the','a');
console.log(String(txt));
console.log(String(txt2));
