

function py2js_str(v) {
    if (v && v.toFixed) {
        if (Math.floor(v) != v) {
            return v.toFixed(12);
        }
    }
    return new String(v);
}


// generated by py2js from tests/strings/rfind.py


var __name__ = '__main__';


s='the quick brown quick the fox';

i=s.lastIndexOf('quick');
console.log(String(py2js_str(i)));

i=s.lastIndexOf('dog');
console.log(String(py2js_str(i)));

i=s.lastIndexOf('the');
console.log(String(py2js_str(i)));
