


function Generator(container) {
        var isarray = (container instanceof Array);
        var isstring = (typeof(container) == 'string');
        if (container.__iter__) {
                this.values = [];
                this.iterator = container.__iter__();
        } else if (isarray || isstring) {
                this.values = container;
        } else {
                this.values = [];
                for(key in container) {
                        this.values.push(key);
                }
        }
        this.index = 0;
}

Generator.prototype.nextValue = function() {
        if (this.iterator) {
                try {
                        return this.iterator.next();
                } catch( e ) {
                        this.iterator_exhausted = true;
                        return null;
                }
        }
        else if (this.index < this.values.length) {
                return this.values[this.index++];
        } else {
                this.index++;
                return null;
        }
}

Generator.prototype.hadMore = function() {
        if (this.iterator_exhausted) {
                return false;
        }
        return (this.index-1) < this.values.length;
}





function py2js_rstrip(str,chars) {
    var i = str.length-1;    
    while(i >= 0) {
        if (chars.indexOf(str.slice(i,i+1)) == -1) {
            break;
        }            
        i--;
    }
    if (i < (str.length-1)) {
        if (i < 0) {
            return "";
        }
        return str.slice(0,i+1);
    }
    return str;
}


// generated by py2js from tests/strings/rstrip0.py


var __name__ = '__main__';


s1='abc\n\n\n';

s2='abc\n\t \n';

s3='abc ';


container_py2js_1=[s1,s2,s3];
var generator_py2js_2 = new Generator(container_py2js_1);
for(s=generator_py2js_2.nextValue();generator_py2js_2.hadMore();s=generator_py2js_2.nextValue()) {
    console.log(String((('original(' + s) + ')')));
    console.log(String((('strip(' + py2js_rstrip(s,"\n\t ")) + ')')));
}
