// generated by py2js from tests/strings/ulcase.py


var __name__ = '__main__';


str='aBcddEzUh';
console.log(String(str));

str=str.toUpperCase();
console.log(String(str));

str=str.toLowerCase();
console.log(String(str));
